// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_ConsoleView_BODY

/************************************************************
 ConsoleView class body
 ************************************************************/

// include associated header file
#include "RootElement/ConsoleView.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of ConsoleView class body
 ************************************************************/
