// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_CONSOLEVIEW_H
#define ROOTELEMENT_CONSOLEVIEW_H

/************************************************************
 ConsoleView class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/SlideWidget.h"
#include "RootElement/Ui_ConsoleView.h"

/************************************************************/
/**
 * 
 */
class ConsoleView: public SlideWidget {

	/**
	 * 
	 */
	Ui_ConsoleView UI;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of ConsoleView class header
 ************************************************************/

#endif
