// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_COORDINATETRANSFORMATION_H
#define ROOTELEMENT_COORDINATETRANSFORMATION_H

/************************************************************
 CoordinateTransformation class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class CoordinateTransformation {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of CoordinateTransformation class header
 ************************************************************/

#endif
