// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_CoordinateTransformation_BODY

/************************************************************
 CoordinateTransformation class body
 ************************************************************/

// include associated header file
#include "RootElement/CoordinateTransformation.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of CoordinateTransformation class body
 ************************************************************/
