// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_DataView_BODY

/************************************************************
 DataView class body
 ************************************************************/

// include associated header file
#include "RootElement/DataView.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @param *current 
 * @param *previous 
 */
void DataView::on_dataList_currentItemChanged(QTreeWidgetItem /*in*/*current,
		QTreeWidgetItem /*in*/*previous) {
}

/**
 * 
 * @param &arg1 
 */
void DataView::on_searchBar_textChanged(QTableWidget /*in*/&arg1) {
}

/************************************************************
 End of DataView class body
 ************************************************************/
