// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_Database_BODY

/************************************************************
 Database class body
 ************************************************************/

// include associated header file
#include "RootElement/Database.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 */
void Database::satList() {
}

/**
 * 
 */
void Database::Setting() {
}

/**
 * 
 * @return  
 */
Satellite Database::Satellite() {
}

/************************************************************
 End of Database class body
 ************************************************************/
