// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_DATABASE_H
#define ROOTELEMENT_DATABASE_H

/************************************************************
 Database class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/Satellite.h"

/************************************************************/
/**
 * 
 */
class Database {
public:
	/**
	 * 
	 */

	/**
	 * 
	 */
	undefined Attribute1;

	/**
	 * 
	 */
	void satList();

	/**
	 * 
	 */
	void Setting();

	/**
	 * 
	 * @return  
	 */
	Satellite Satellite();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Database class header
 ************************************************************/

#endif
