// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_MainGUI_BODY

/************************************************************
 MainGUI class body
 ************************************************************/

// include associated header file
#include "RootElement/MainGUI.h"

// Derived includes directives

// static attributes (if any)
/**
 * 
 */
EDouble MainGUI::widthFullHD = 1920.0;
/**
 * 
 */
Constants MainGUI::constants = 1234.0;

/**
 * 
 */
void MainGUI::startCalculationOfTrack() {
}

/**
 * 
 */
void MainGUI::appendCoordinates() {
}

/**
 * 
 */
void MainGUI::showRecievedTrack() {
}

/**
 * 
 */
void MainGUI::editSatellite() {
}

/**
 * 
 */
void MainGUI::mouseMoveGeoPosition() {
}

/**
 * 
 */
void MainGUI::zoomChanged() {
}

/**
 * 
 */
void MainGUI::mouseMoveEvent() {
}

/**
 * 
 */
void MainGUI::mouseReleaseEvent() {
}

/**
 * 
 */
void MainGUI::mousePressEvent() {
}

/**
 * 
 */
void MainGUI::on_actionAddNewSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionOpenSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionSaveSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionUsedDocuments_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionImportSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionExportSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionUndo_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionRedo_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionCut_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionCopy_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionPast_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionSelectAll_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionElse_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionCenterMap_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionZoomMap_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionCompleteMap_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionZoomSteps_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionProvideSatelite_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionDataViewer_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionPolarView_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionConsole_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionTrajectory_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionMinimize_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionZoomMainView_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionForwardAll_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionSearchHelp_triggered() {
}

/**
 * 
 */
void MainGUI::on_actionAlphaSatHelp_triggered() {
}

/**
 * 
 * @param style 
 */
void MainGUI::setLineStyle(Marble::GeoDataStyle /*in*/style) {
}

/**
 * 
 * @param m 
 * @param x 
 * @param x0 
 * @param y0 
 */
void MainGUI::linearPoint(EDouble /*in*/m, EDouble /*in*/x, EDouble /*in*/x0,
		EDouble /*in*/y0) {
}

/************************************************************
 End of MainGUI class body
 ************************************************************/
