// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_OrbitalMechanics_BODY

/************************************************************
 OrbitalMechanics class body
 ************************************************************/

// include associated header file
#include "RootElement/OrbitalMechanics.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of OrbitalMechanics class body
 ************************************************************/
