// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_ORBITALMECHANICS_H
#define ROOTELEMENT_ORBITALMECHANICS_H

/************************************************************
 OrbitalMechanics class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class OrbitalMechanics {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of OrbitalMechanics class header
 ************************************************************/

#endif
