// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_PolarView_BODY

/************************************************************
 PolarView class body
 ************************************************************/

// include associated header file
#include "RootElement/PolarView.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of PolarView class body
 ************************************************************/
