// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_POLARVIEW_H
#define ROOTELEMENT_POLARVIEW_H

/************************************************************
 PolarView class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/SlideWidget.h"
#include "RootElement/Ui_PolarView.h"

/************************************************************/
/**
 * 
 */
class PolarView: public SlideWidget {

	/**
	 * 
	 */
	Ui_PolarView UI;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of PolarView class header
 ************************************************************/

#endif
