// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_Satellite_BODY

/************************************************************
 Satellite class body
 ************************************************************/

// include associated header file
#include "RootElement/Satellite.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @return success 
 */
::PrimitiveTypes::Boolean Satellite::pushSatellite() {
}

/**
 * 
 */
void Satellite::setNumber() {
}

/**
 * 
 */
void Satellite::setName() {
}

/**
 * 
 */
void Satellite::setESN() {
}

/**
 * 
 */
void Satellite::setClassify() {
}

/**
 * 
 */
void Satellite::setEpoch_y() {
}

/**
 * 
 */
void Satellite::setEpoch() {
}

/**
 * 
 */
void Satellite::set_d_dt_MM() {
}

/**
 * 
 */
void Satellite::set_d_dt2_MM() {
}

/**
 * 
 */
void Satellite::setDrag() {
}

/**
 * 
 */
void Satellite::setIncli() {
}

/**
 * 
 */
void Satellite::setRAN() {
}

/**
 * 
 */
void Satellite::setEcctr() {
}

/**
 * 
 */
void Satellite::setMA() {
}

/**
 * 
 */
void Satellite::setMM() {
}

/**
 * 
 */
void Satellite::setRNE() {
}

/**
 * 
 */
void Satellite::Operation1() {
}

/************************************************************
 End of Satellite class body
 ************************************************************/
