// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_SATLIST_H
#define ROOTELEMENT_SATLIST_H

/************************************************************
 SatList class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"
#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class SatList {
public:
	/**
	 * 
	 */
	QTableWidget name[];
	/**
	 * 
	 */
	::PrimitiveTypes::Integer number[];
	/**
	 * 
	 */
	::PrimitiveTypes::Integer ESN[];
	/**
	 * 
	 */
	::PrimitiveTypes::Integer *ID;

	/**
	 * 
	 */
	void setSatList();

	/**
	 * 
	 * @return name 
	 * @return number 
	 * @return RNE 
	 */
	::PrimitiveTypes::String subSet();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of SatList class header
 ************************************************************/

#endif
