// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_SatList_BODY

/************************************************************
 SatList class body
 ************************************************************/

// include associated header file
#include "RootElement/SatList.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 */
void SatList::setSatList() {
}

/**
 * 
 * @return name 
 * @return number 
 * @return RNE 
 */
::PrimitiveTypes::String SatList::subSet() {
}

/************************************************************
 End of SatList class body
 ************************************************************/
