// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_Settings_BODY

/************************************************************
 Settings class body
 ************************************************************/

// include associated header file
#include "RootElement/Settings.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @return success 
 */
::PrimitiveTypes::Boolean Settings::pushSetting() {
}

/************************************************************
 End of Settings class body
 ************************************************************/
