// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_SETTINGS_H
#define ROOTELEMENT_SETTINGS_H

/************************************************************
 Settings class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

/************************************************************/
/**
 * 
 */
class Settings {
public:
	/**
	 * 
	 */
	::PrimitiveTypes::Integer ID;
	/**
	 * 
	 */
	::PrimitiveTypes::Integer date;

	/**
	 * 
	 * @return success 
	 */
	::PrimitiveTypes::Boolean pushSetting();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Settings class header
 ************************************************************/

#endif
