// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define RootElement_SlideWidget_BODY

/************************************************************
 SlideWidget class body
 ************************************************************/

// include associated header file
#include "RootElement/SlideWidget.h"

// Derived includes directives

// static attributes (if any)
/**
 * 
 */
QRect SlideWidget::m_slideWidgetHide;
/**
 * 
 */
QRect SlideWidget::m_slideWidgetShow;
/**
 * 
 */
EBoolean SlideWidget::m_hide = false;

/**
 * 
 */
void SlideWidget::on_pushSlideWidget_clicked() {
}

/**
 * 
 */
void SlideWidget::mouseMoveEvent() {
}

/**
 * 
 */
void SlideWidget::mouseReleaseEvent() {
}

/**
 * 
 */
void SlideWidget::mousePressEvent() {
}

/************************************************************
 End of SlideWidget class body
 ************************************************************/
