// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_SLIDEWIDGET_H
#define ROOTELEMENT_SLIDEWIDGET_H

/************************************************************
 SlideWidget class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "EcorePrimitiveTypes/Pkg_EcorePrimitiveTypes.h"
#include "RootElement/Constants.h"
#include "RootElement/Pkg_RootElement.h"
#include "RootElement/Ui_SlideWidget.h"

/************************************************************/
/**
 * 
 */
class SlideWidget {

	/**
	 * 
	 */
	Ui_SlideWidget UI;
	/**
	 * 
	 */
	static QRect m_slideWidgetHide;
	/**
	 * 
	 */
	static QRect m_slideWidgetShow;
	/**
	 * 
	 */
	static EBoolean m_hide;
	/**
	 * 
	 */
	Constants constants;

	/**
	 * 
	 */
	void on_pushSlideWidget_clicked();

	/**
	 * 
	 */
	void mouseMoveEvent();

	/**
	 * 
	 */
	void mouseReleaseEvent();

	/**
	 * 
	 */
	void mousePressEvent();
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of SlideWidget class header
 ************************************************************/

#endif
