// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_UI_DATAVIEW_H
#define ROOTELEMENT_UI_DATAVIEW_H

/************************************************************
 Ui_DataView class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class Ui_DataView {
public:
	/**
	 * 
	 */
	QLineEdit searchBar;
	/**
	 * 
	 */
	QListWidget dataList;
	/**
	 * 
	 */
	QListWidget satellitData;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Ui_DataView class header
 ************************************************************/

#endif
