// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_UI_MAINGUI_H
#define ROOTELEMENT_UI_MAINGUI_H

/************************************************************
 Ui_MainGui class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class Ui_MainGui {
public:
	/**
	 * 
	 */
	QAction actionAddNewSatelite;
	/**
	 * 
	 */
	QAction actionOpenSatelite;
	/**
	 * 
	 */
	QAction actionSaveSatelite;
	/**
	 * 
	 */
	QAction actionUsedDocuments;
	/**
	 * 
	 */
	QAction actionImportSatelite;
	/**
	 * 
	 */
	QAction actionExportSatelitet;
	/**
	 * 
	 */
	QAction actionUndo;
	/**
	 * 
	 */
	QAction actionRedo;
	/**
	 * 
	 */
	QAction actionCut;
	/**
	 * 
	 */
	QAction actionCopy;
	/**
	 * 
	 */
	QAction actionPast;
	/**
	 * 
	 */
	QAction actionSelectAll;
	/**
	 * 
	 */
	QAction actionElse;
	/**
	 * 
	 */
	QAction actionCenterMap;
	/**
	 * 
	 */
	QAction actionZoomMap;
	/**
	 * 
	 */
	QAction actionCompleteMap;
	/**
	 * 
	 */
	QAction actionVisibleZone;
	/**
	 * 
	 */
	QAction actionZoomSteps;
	/**
	 * 
	 */
	QAction actionProvideSatelite;
	/**
	 * 
	 */
	QAction actionDataViewer;
	/**
	 * 
	 */
	QAction actionPolarView;
	/**
	 * 
	 */
	QAction actionConsole;
	/**
	 * 
	 */
	QAction actionTrajectory;
	/**
	 * 
	 */
	QAction actionMinimize;
	/**
	 * 
	 */
	QAction actionZoomMainView;
	/**
	 * 
	 */
	QAction actionForwardAll;
	/**
	 * 
	 */
	QAction actionSearchHelp;
	/**
	 * 
	 */
	QAction actionAlphaSatHelp;
	/**
	 * 
	 */
	undefined centralWidget;
	/**
	 * 
	 */
	Marble::MarbleWidget marbleMap;
	/**
	 * 
	 */
	undefined coordinates;
	/**
	 * 
	 */
	undefined menuBar;
	/**
	 * 
	 */
	undefined mainToolBar;
	/**
	 * 
	 */
	undefined statusBar;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Ui_MainGui class header
 ************************************************************/

#endif
