// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROOTELEMENT_UI_SLIDEWIDGET_H
#define ROOTELEMENT_UI_SLIDEWIDGET_H

/************************************************************
 Ui_SlideWidget class header
 ************************************************************/

#include "RootElement/Pkg_RootElement.h"

#include "RootElement/Pkg_RootElement.h"

/************************************************************/
/**
 * 
 */
class Ui_SlideWidget {
public:
	/**
	 * 
	 */
	QWidget mainWidget;
	/**
	 * 
	 */
	QWidget centralWidget;
	/**
	 * 
	 */
	QPushButton pushSlideWidget;
	/**
	 * 
	 */
	QLabel moveSlideWidget;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Ui_SlideWidget class header
 ************************************************************/

#endif
